name: Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Relay (generate types)
        run: yarn all:relay
        env:
          CI: true

      - name: Format
        run: yarn prettier
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Update schema
        run: yarn update-schema
        env:
          CI: true

      - name: Test
        run: yarn jest
        env:
          CI: true
